name: Publish to GH Pages

on:
  release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Install
        run: npm ci
      -
        name: Build
        run: npm run build
      -
        name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1.2.5
        with:
          target_branch: gh-pages
          keep_history: true
          build_dir: dist
          fqdn: vapurrmaid.ca
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

