name: Pull Request (master)

on:
  pull_request:
    branches:
      - master

jobs:
  check-pr:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Install
        run: npm install
      -
        name: Lint
        run: npm run lint
      -
        name: Vulnerability Scsan
        run: npm audit
